### ISSUE TITLE
"Select console type" is now a choice in the dropdown

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#111]
* [x] blocked on https://github.com/patternfly/patternfly-react/pull/5693

PR #97 introduced a regression: I can now literally select "select console type" in the dropdown:

![image](https://user-images.githubusercontent.com/200109/114827233-b889f100-9dc8-11eb-9b30-e854e45f8fdc.png)

**Comment by KKoukiou** [comment]
Some patternfly/react-core update must have broken this. 

I posted a fix upstream:
https://github.com/patternfly/patternfly-react/pull/5678

**Comment by KKoukiou** [comment]
Blocked again now on https://github.com/patternfly/patternfly-react/pull/5693

**Comment by KKoukiou** [comment]
Now it looks like this:
![Screen Shot 2021-05-05 at 09 02 45](https://user-images.githubusercontent.com/14921356/116970032-87119080-acb7-11eb-89f4-dc15cdad3d18.png)


The 'Select console type' is missing in our case, because in the code we preselect a console internally.
For users which don't have an initial console type choice, (in other projects) the 'Select console type' button will be visible only for the first time selection.
