### ISSUE TITLE
VM reboots without confirmation

### ISSUE THREAD

**Issue by Larse99** [cockpit-project/cockpit-machines#1157]
Hi

I've experienced this strange bug. Whenever I press "Reboot" (opnieuw opstarten), it will give me a prompt like: Do you really want to restart X? In theory a really nice feature. But my VMs reboot before I even press "Yes". See attached video.

https://github.com/cockpit-project/cockpit-machines/assets/50380574/b1024f5c-58f7-4aae-b7ca-b6adf9fe20e1

**Comment by skobyda** [comment]
Hello. Thanks for report.

This has been fixed in https://github.com/cockpit-project/cockpit-machines/pull/1144 

Which version of cockpit-machines do you use? This should be fixed since cockpit-machines-294, so closing this issue as fixed.

 If you are however experiencing this bug in version >= 294, please reopen
