### ISSUE TITLE
Watching is not implemented, use fswatch1

### ISSUE THREAD

**Issue by CapitaineThug** [cockpit-project/cockpit-machines#1316]
Bonjour, j'ai un problème lorsque je créée une machine virtuelle avec Cockpit-Machines: Je décide d'utiliser un média d'installation ISO copié localement sur le serveur mais l'erreur suivante appraît et ne me permet pas de visualiser mon arborescence:

![image](https://github.com/cockpit-project/cockpit-machines/assets/104926772/733d3866-0692-4f76-b2e9-ab0a53f2c69f)

Après quelques recherches, j'ai essayé de changer les droits d'accès au fichier mais cela n'a rien changé...

Que faudrait-il faire, j'ai déjà essayé de mette à jour le système.
Merci pour l'aide.

**Comment by martinpitt** [comment]
Bonjour,

s'il vous plaît, essayez de parler anglais ici -- nos developpeurs ne parlent pas français bon.. :grin: 

Quel OS utilisez-vous (Ubuntu, Fedora, ...) ? Quelles sont les versions des cockpit-machines et cockpit-bridge ? SVP mettez les à la dernière version.

----

English:

cockpit-machines does not use fslist1, fswatch1 directly at all, and cockpit.file() only without watching. This is cockpit-components-file-autocomplete.jsx , and that issue was fixed in https://github.com/cockpit-project/cockpit/commit/a3fad8f6e710375391d6e5a5da350e81ec11813d . So this looks like it's using the Python bridge (new cockpit-bridge) together with an old cockpit-machines version.

Which operating system do you use? What are the package versions of cockpit-machines and cockpit-bridge? Please try to upgrade them both to the latest version.

**Comment by CapitaineThug** [comment]
Thanks for the quick answer, I'm using the following Linux version:

- Ubuntu Server 22.04.3 LTS

All Cockpit packages are in the following version
![image](https://github.com/cockpit-project/cockpit-machines/assets/104926772/6f217ca7-7685-4d84-b9f2-731fcbb98b5f)

My OS is updated, I used apt-update and apt-upgrade. Should I consider upgrading to 23.10 ?

**Comment by martinpitt** [comment]
Yes, what I thought -- your cockpit-bridge packge is from "jammy-backports" (version 300), but your cockpit-machines package is an old version from jammy release (265). Please update to version [300 from jammy-backports](https://launchpad.net/ubuntu/+source/cockpit-machines):
```
sudo apt install -t jammy-backports cockpit-machines
```

**Comment by martinpitt** [comment]
... and cockpit-podman and cockpit-pcp as well while you are it :grin:

**Comment by CapitaineThug** [comment]
It worked !! Thank you so much for your help (now the gui is in dark mode !).
