### ISSUE TITLE
Feature Request - Add Replace SPLICE devices to Create VM

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#1550]
Please add a checkbox for 'Replace SPLICE devices' to the UI for Create VM.
I know you can select Edit instead and then replace them but a checkbox here would be better so that you can select 'Create and run'

Also.. Can the problem itself not be fixed?  It seems like with this new option you know what the issue is now?
Rel: https://github.com/cockpit-project/cockpit-machines/issues/1210

**Comment by martinpitt** [comment]
Sorry, we will not add a spice config to the creation dialog. The option for existing VMs is already a bad UI workaround for an underlying design problem, and adding it to the creation dialog is purely an "unbreak my VM" option. This really needs to be fixed in qemu, see https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1492621

**Comment by tgwaste** [comment]
I wonder why that 8 year old bug only started causing me problems a year ago.
