### ISSUE TITLE
migration: Clicking on the "Duration:" label or the circled question mark (popover trigger) toggles the checkbox

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-machines#160]
This is because the 'Duration' is literally the label for the checkbox. Labels behave like, clicking on them selects their content, this so it's not so unexpected. But not desired in this case.

Reported on https://github.com/cockpit-project/cockpit-machines/pull/15#issuecomment-838755703

**Comment by garrett** [comment]
Clicking on the label should select the widget. That's important and how forms work. Breaking that breaks all kinds of accessibility and makes things not act as expected.

But clicking the (?) should not check/uncheck the checkbox.

The fix is either:
1. move the icon outisde of the label
2. add an event.preventDefault() for when the (?) is checked

Fix # 1 is more proper and the preferred solution, as the (?) isn't actually part of the label. I'm not sure if PF4 would support the (?) icon next to the label if it's not inside it, however.
