### ISSUE TITLE
JS Error when trying to delete VM in web UI

### ISSUE THREAD

**Issue by bobafett2010** [cockpit-project/cockpit-machines#178]
Cockpit version: xxx
OS:
Page: 

When trying to delete a VM in the web UI, I am presented with an error that pops an "OOOPS" warning next to the Administrative access. It appears to be a Uncaught TypeError. I only started experiencing this today. I did notice that the volume attached to the VM actually does get deleted however the VM itself is not deleted.

Steps to reproduce

1. Create a VM
2. Attempt to Delete the VM
3.

![image](https://user-images.githubusercontent.com/51348658/119101399-f3460100-b9e6-11eb-9591-d7f78855cc05.png)
![image](https://user-images.githubusercontent.com/51348658/119101371-e88b6c00-b9e6-11eb-99b4-3328cd36daf0.png)

**Comment by marusak** [comment]
Can you please specify version of `cockpit-machines`?

**Comment by martinpitt** [comment]
I fixed this recently in commit b5850e7539211ce6df77008c05ae5b61fcf6bc28 -- sorry for the mess!

This is fixed in version 244.1, which you can get for [Fedora 34](https://bodhi.fedoraproject.org/updates/FEDORA-2021-380660d6cd) or [Fedora 33](https://bodhi.fedoraproject.org/updates/FEDORA-2021-15d8576d18) in updates-testing. If you could officially test and +1 these updates, they'd make it into updates faster. Thank you!

**Comment by bobafett2010** [comment]
Can confirm that this issue has been fixed. Thank you so much!
