### ISSUE TITLE
Cannot attach any 2nd drive after reboot

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#193]
VM Will not boot. I get a Permission denied issue on the drive:

internal error: process exited while connecting to monitor: 2021-06-05T03:58:37.910878Z qemu-system-x86_64: -blockdev {"driver":"file","filename":"/bak/disks2/test","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: Could not open '/bak/disks2/test': Permission denied

I can't find any means to fix this.  Worked perfect before reboot

[ 1189.631621] audit: type=1400 audit(1622866287.768:170): apparmor="DENIED" operation="open" profile="libvirt-dba8a0f2-29f4-4043-8357-b58458282000" name="/bak/disks/home-bak" pid=11689 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Update: The only way I could fix it

```
# cat /etc/apparmor.d/libvirt/TEMPLATE.qemu
#
# This profile is for the domain whose UUID matches this file.
#

#include <tunables/global>

profile LIBVIRT_TEMPLATE flags=(attach_disconnected) {
  #include <abstractions/libvirt-qemu>
  "/bak/disks/" r,
  "/bak/disks/**" rwk,
}
```

**Comment by KKoukiou** [comment]
Hey @tgwaste this is an ubuntu bug in libvirt - see https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1677398.
 
Since you use a custom path for your disks (not the /var/lib/libvirt/images default one) you are affected by it.

Therefore you need to manuallly adjust that Apparmor profile to not block qemu from accessing that directory.

Your workaround is correct but for being specific for future reference people can use:
https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1677398/comments/44

And more info for libvirt/Apparmor integration can be seen in:
https://gitlab.com/apparmor/apparmor/-/wikis/Libvirt.
