### ISSUE TITLE
Creation of Ubuntu 'Workstation' 20.04 VMs fails - requires the user-password to be set, but no field available to set it

### ISSUE THREAD

**Issue by danielkrajnik** [cockpit-project/cockpit-machines#327]
Occurs on Cockpit machines, which was installed from the apt package manager on Ubuntu 21.04

Ubuntu Workstation with Download OS option can't proceed, because it requires user-password set. Please let's add this field to the menu. Only 'Server' works as it only requires root password.

Full error:
ERROR ubuntu20.04 requires the user-password to be set. Domain installation does not appear to have been successful. If it was, you can restart your domain by running: virsh --connect qemu:///system start test2 otherwise, please restart your installation.

**Comment by KKoukiou** [comment]
This is supported since cockpit-machines 240.
Introduced with commit https://github.com/cockpit-project/cockpit/commit/07fbcc88c30ce3d6c2b39e483ad2d0913acf4e9f
![Screen Shot 2021-08-30 at 09 25 45](https://user-images.githubusercontent.com/14921356/131301849-540e7b45-3fcb-45a7-8263-b0dd269fd42d.png)


Try installing the cockpit-machines package from backports. https://packages.ubuntu.com/hirsute-backports/cockpit-machines
