### ISSUE TITLE
Support for lvm thin pool storage?

### ISSUE THREAD

**Issue by hurenkam** [cockpit-project/cockpit-machines#479]
I would like to use an LVM Thin provisioned pool for storing my VM drives, but cockpit-machines storage pools does not seem to support thin pools.
About 9 out of my 10 VMs are using thin provisioning, so would very much like to be able to create and use that type of storage pool in the cockpit-machines application.

**Comment by hurenkam** [comment]
Just an afterthought, would it not make more sense to have this plugin depend on cockpit-storaged, so that it can simply import pools that are already defined there? Seems to make more sense to me at least.

**Comment by skobyda** [comment]
Hello @hurenkam . Correct me if I'm wrong, but cannot you create thin pool by `lvcreate --type thin-pool ...` and then create volumes with `lvcreate --type thin -V ... --name ... --thin-pool ...`, and then attach such pool and use cockpit-machines UI? From what I understand, libvirt doesn't differentiate if LVM pool is thin or not, so it should be possible to attach thin pool just like any other LVM pool.
Or in order to add lvm thin storage pool, do you need to input some additional information in storage pool creation dialog?
![Screenshot from 2021-12-16 01-11-49](https://user-images.githubusercontent.com/42733240/146284574-7b57a23c-d2da-4073-aa2f-dca31f1902d4.png)

**Comment by hurenkam** [comment]
>From what I understand, libvirt doesn't differentiate if LVM pool is thin or not, so it should be possible to attach thin pool just like any other LVM pool.
The problem is that in the cockpit-machines dialog, there is no way to create storage pool that uses a thin pool. And if you use the volume group in which the thin pool resides, then logical volumes that reside within a thin pool are not listed by the ui.

> Or in order to add lvm thin storage pool, do you need to input some additional information in storage pool creation dialog?
For a thin pool, you would need to provide the volume group, and the name of the pool within the volume group to uniquely define the pool, since more than one thin-pool can live within a single volume group.

I have a volume group 'vm1' in which I have a thin pool called 'pool' with lots of disks for virtual machines. However when I create a storage pool with source volume group 'vm1', none of those volumes are listed. And I seem to be unable to specifically create a storage pool that uses the thin pool identified by the logical volume 'vm1/pool' as source.

**Comment by hurenkam** [comment]
It looks like this is a libvirt limitation, I recently tried to create a vm using virt-manager and am running into the same problem. This is a definitely a deal breaker for me, I will stick with proxmox for now.

**Comment by KKoukiou** [comment]
Closing as there is nothing we can help on with this in this project. Blocked on the upstream fix in libvirt.
