### ISSUE TITLE
Cockpit Machines depends on adwaita icon theme, gtk, libwayland, SDL, etc.  

### ISSUE THREAD

**Issue by IceWreck** [cockpit-project/cockpit-machines#496]
I was trying to install cockpit-machines on Fedora 35 minimal and it has a shitton of unrequired dependencies.

Why are icon themes, gnome's dconf, gtk, tracker-miners, libwayland, SDL and other GUI specific things (around 250 packages total) required to manage VMs on a headless server ? 

```bash
➜  ~ dnf repoquery --requires cockpit-machines
Last metadata expiration check: 0:07:04 ago on Friday 24 December 2021 07:31:21 PM.
cockpit-bridge >= 215
libvirt-client
libvirt-daemon-kvm
libvirt-dbus >= 1.2.0
```

I looked at these individually and `libvirt-daemon-kvm` is the culprit. I found [this](https://bugzilla.redhat.com/show_bug.cgi?id=1823044 ) issue on redhat bugzilla and they recommend using `libvirt-daemon-driver-qemu` and some other things instead of the full `libvirt-daemon-kvm` package.

Are there any workarounds where I could use cockpit machines without GUI dependencies ?

**Comment by KKoukiou** [comment]
Hey @IceWreck thanks for reporting.

An in-place replacement of "libvirt-daemon-kvm" with "libvirt-daemon-driver-qemu" and "qemu-kvm-core in our dependencies is unfortunately not sufficient.

Firstly we should depend on all libivirt-daemon-driver-* packages (as libvirt-daemon-driver-nodedev, libvirt-daemon-driver-interface, libvirt-daemon-driver-storage ...) for multiple features as of managing node devices, interfaces and storage for example. That's however not problematic.

Secondly "qemu-kvm-core" alone is also not sufficient.
I am sure we need all "qemu-block-" packages for supporting different storage options for example. 

All in all, I don't think this project is the correct place to clean up this dependency list.
How I see it, is that it's libvirt's responsibility to make sure they don't bring in, qemu-ui-gtk and other qemu-ui-* packages, which they are definitely not using. And this is currently not possible in a clean way because of how qemu does it's packaging. 

So, I agree that it's a bug that libvirt-qemu-kvm depends indirectly on qemu-ui-* packages, and this should be fixed in these two underlying projects, not here.

**Comment by KKoukiou** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1823044#c8 the work in in progress to split out these rpms. If you want to track this I suggest you open an issue to qemu project on bz.
