### ISSUE TITLE
Cockpit Virtualization very slow

### ISSUE THREAD

**Issue by Abjorge95** [cockpit-project/cockpit-machines#54]
Greetings,

I just installed Cockpit on my Ubuntu 20.04 Server with AMD Ryzen 5 and 16 GB of Ram.

All is working fine, but all that is related with virtualisation is slow, installing a new VM is super slow even assigning 8 GB of Ram and 4 vCPU takes over 2 hours to install (I Tryed the two ways, the use preloaded ISO of new Ubuntu 20.04 or loading my own).

The using of the VM it self is slow and my main server is showing always super high Ram usage even when the VM is only using less then 1 GB of Ram

I wonder if I'm doing something wrong.

**Comment by KKoukiou** [comment]
@Abjorge95 doing an issue cleanup here. So this issue is very specific to your system, and unfortunately I can't help you more without doing live debugging on your system. As still is very old and does not help other users to solve similiar issues will close it.

If you still use cockpit-machines for managing your VMs and you suffer from such performance problems, I suggest you reach out for help again, maybe even better directly to libvirt or qemu developers.
