### ISSUE TITLE
Network Bridge Operation not Supported

### ISSUE THREAD

**Issue by invertium** [cockpit-project/cockpit-machines#543]
Cockpit version: Version 225.
OS:
Page: /machines

I'm trying to add a new network interface to bridge to my network, however when I select the following options:
![image](https://user-images.githubusercontent.com/15930333/90506911-4ab3f980-e155-11ea-9e56-7b90bd6719eb.png)
I get Unable to add bridge enp3s0 port vnet0: Operation not supported

Steps to reproduce

1. Create new VM (Ubuntu Server 19.04) on Debian
2. Create New Network Interface with the options above
3. Try to start machine

**Comment by garrett** [comment]
Oh what happened with the layout in this screenshot?

![oddity in the screenshot](https://user-images.githubusercontent.com/12600975/100071785-ca511300-2e7e-11eb-914d-f0789680c09d.png)

I'm guessing the browser is too narrow and the label width is too long or something like that?

@aaroncnb: What size is your browser? Are you able to take a full page screenshot (I'm mainly interested in the width, as "breakpoints" are tied to widths... you could crop the height out.)

(It's a different bug, of course, but we should fix this too.)

**Comment by FacePalmDev** [comment]
When I try this using my wifi connection it drops. It acts as though it doesn't recognise the Key

**Comment by luispabon** [comment]
The reason is because this option requires that the source network interface is a bridge, not a regular network interface. 

The solution is to go to the networking tab, add a bridge, adding the network interface in question to it. Then, when you create the network interface on your VM, select this bridge as the source.

Cockpit should really filter out any network interfaces that aren't bridges on that dropdown.

**Comment by garrett** [comment]
> Cockpit should really filter out any network interfaces that aren't bridges on that dropdown.

@luispabon: I think the fix for this landed in https://github.com/cockpit-project/cockpit-machines/pull/929, which happened on 2 Feb... so it should be filtered in Cockpit 285 and after. (Current version of Cockpit, as of writing this comment, is 288.)

If you don't have a filtered list, please update Cockpit on your system.

Updating is pretty straightforward for most distributions; you just upgrade everything on your system and you should have it. However, for Debian, Ubuntu, and derivatives, you need to use backports to get the latest version of Cockpit, as specified @ https://cockpit-project.org/running.html#debian

**Comment by luispabon** [comment]
Thank you @garrett  , I do actually have cockpit installed in ubuntu from backports, but weirdly the latest version of cockpit-machines available is 283 whereas other main cockpit packages sit at 287, for which I got an update just this weekend:

![image](https://user-images.githubusercontent.com/6388823/227895665-818a8b5e-d7b8-4b85-9b85-3fd22846f3d9.png)

**Comment by garrett** [comment]
@luispabon: The versions of Cockpit-Machines (and Cockpit-Podman) trail the Cockpit release... but the latest is cockpit-machines 286, according to https://cockpit-project.org/blog/cockpit-288.html (but sometimes it takes a little while to get into backports)

But https://cockpit-project.org/blog/cockpit-286.html lists Cockpit-Machines 284, which should have the fix... so it's odd that Cockpit-Machines is lagging behind Cockpit in the backports like this.

**Comment by luispabon** [comment]
In my experience the ubuntu backports for cockpit typically lag one release behind. Not sure why the machines plugins specifically is 2 releases behind. In any case I'm glad it's sorted, thank you 👍

**Comment by martinpitt** [comment]
Sorry, that's just how it works -- there's a lot of process, CI, and wait times between Debian upload, Ubuntu imports, and doing the backports.
