### ISSUE TITLE
Unable to remotely connect to Windows 10 Pro Cockpit VM with VPN

### ISSUE THREAD

**Issue by schevenin** [cockpit-project/cockpit-machines#551]
I am going to try to explain my issue as thoroughly as possible as I have not been able to find anything similar to my issue anywhere else. The closest I have found is #73. I was hoping that by posting this, I could at least head a step closer in the right direction.

Relevant services on my machine:
- Ubuntu 20.04.3 LTS
- Docker 2.11.0 w/ WireGuard VPN container (image: ghcr.io/linuxserver/wireguard:latest)
- Cockpit (Version 215) with a Windows 10 Pro VM (remote desktop enabled)

Here is what (in theory) I would like to have working: My goal was to have cockpit running a VM that I could Remote Desktop or VNC into after a connection to my VPN. My thinking was this is a better option than just opening port 3389 to WAN, which has been successful on this setup before. My issue is that it doesn't seem to like my connection on RDS/VNC when I try to connect to it. When I log into the machine on the Cockpit Web interface the machine has internet and everything seems fine.

More info:
- My ubuntu machine's local IP is 192.168.1.250
- My VM's local IP is 192.168.122.87

Here is the configuration for the Network Interface in Cockpit:
- Type: Bridge
- Model type: e1000 (PCI, Legacy)
- Source: virbr0

When I use that Network Interface above, I am also unable to connect when I am on my local network. Instead, when I use a direct connection to eno1 I see that the IP address of the VM changes to a 192.168.1.X subnet and I am able to connect to it on my local network, but still not through the VPN.

Any ideas?

**Comment by garrett** [comment]
Could it be a firewall issue on your host machine?

If you have a firewall enabled, make sure it has port `3389` open and available.

You could test this from Cockpit. The Network page has a Firewall sub-page. It has a quick toggle to enable/disable the firewall. If you can access the machine when the firewall is disabled, then you know that's the problem. 

If you'd like to have the firewall enabled, make sure you add a the `rdp` service (which is associated with TCP port 3389).

The Networking page looks like this:

![Screenshot from 2022-02-03 17-06-56](https://user-images.githubusercontent.com/10246/152380934-1953948a-60c7-4ab9-9aa2-2a9da11b024d.png)

The Firewall page looks like this:

![Screenshot from 2022-02-03 17-07-56](https://user-images.githubusercontent.com/10246/152381119-d0c6918b-0ecb-487e-94df-bc27a6f70063.png)

When you add the `rdp` service, it looks like this:

![image](https://user-images.githubusercontent.com/10246/152380753-b24e6807-825c-4e09-a816-f31b089cfbc8.png)

And it should add a row in your zone like this:

![Screenshot from 2022-02-03 17-05-24](https://user-images.githubusercontent.com/10246/152380771-3430cd9b-6e02-4baf-96e3-d7d65e257066.png)

If the firewall isn't the problem, then hopefully someone else the Cockpit team who is more familiar with the implementation of cockpit-machines can help out!

Otherwise, if the firewall is the problem, I hope this helps out! Please let us know how it goes!

**Comment by schevenin** [comment]
@garrett Thank you for the promptly reply, and I apologize for not getting back to you sooner! I have gone ahead and taken a look at my Cockpit settings inside the Networking tab and am not seeing a Firewall toggle like your screenshots show.

![Cockpit](https://i.imgur.com/DsXGlI6.png)

**Comment by schevenin** [comment]
Something interesting I'd like to add that might help diagnose the issue:

When connected to VPN I am able to ping my host server and get replies, but when I try to ping the Cockpit VM that runs on the host server, I receive multiple "Request timeout for icmp_seq 0" messages followed by a little more after. Here is the screenshot:

!(https://i.imgur.com/8PUrLWO.png)[ping]

**Comment by schevenin** [comment]
For anyone with a similar issue, I was able to solve the issue by setting up the bridge network interface and inside of Remote Desktop, using the default No Gateway option, and instead connecting to the 192.168.122.x IP!
- Type: Bridge
- Model type: e1000 (PCI, Legacy)
- Source: virbr0
