### ISSUE TITLE
Virtual Machine IP listed as unknown when VM connected via Bridge

### ISSUE THREAD

**Issue by akinomeroglu** [cockpit-project/cockpit-machines#61]
Cockpit version: 220
OS:Fedora 32
Page: Machines

I am creating my virtual machines from Cockpit. There is a bridge connection for my machines to reach host network and VM's connect to network via bridge. When I add the VM to bridge machine connected to external DHCP and take IP address but it still shows as Unknown in Network Interfaces tab. In virt-manager I can see the VM's IP.

Steps to reproduce

1. Create a bridge network
2. Create a virtual machine
3. Add this bridge connection from Network Interface 
4. Run VM and see ıf it is getting an IP from DHCP
5. Check network interfaces tab to see IP set to unknown or VM's IP

**Comment by tgwaste** [comment]
This shows IP, but cockpit doesnt in the interface.  Any fix coming for this?
```
# virsh domifaddr --source arp minecraft
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 vnet0      52:54:00:f3:4b:f8    ipv4         192.168.0.53/0
```

**Comment by zippy2** [comment]
> This shows IP, but cockpit doesn't in the interface. Any fix coming for this?
> 
> Edit: Nevermind, the problem with ARP is that you have to connect to the host first before the IP will show up in the arp table which completely defeats the purpose. I hate how much of a PIA it is to get guest information from libcrap.

I'm not sure what libcrap is referring to, but domifaddr has another source "agent" which uses guest agent to obtain the list of IP addresses (see man virsh for more info). BTW: If you are using external DHCP does it also do DNS translation? I mean, VMs can be viewed as another host on the network - how would you get its IPs in general? If you have any clever idea I'm happy to implement it in libvirt (virsh).

**Comment by tgwaste** [comment]
> > This shows IP, but cockpit doesn't in the interface. Any fix coming for this?
> > Edit: Nevermind, the problem with ARP is that you have to connect to the host first before the IP will show up in the arp table which completely defeats the purpose. I hate how much of a PIA it is to get guest information from libcrap.
> 
> I'm not sure what libcrap is referring to, but domifaddr has another source "agent" which uses guest agent to obtain the list of IP addresses (see man virsh for more info). BTW: If you are using external DHCP does it also do DNS translation? I mean, VMs can be viewed as another host on the network - how would you get its IPs in general? If you have any clever idea I'm happy to implement it in libvirt (virsh).

agent has never worked for me.

Im not the best at the networking part but for my hypervisor I typically setup a bridge like so:
apt-get -y install bridge-utils ifupdown

then in /etc/network/interfaces I do:

```
auto lo
  iface lo inet loopback
allow-hotplug eth0
auto br0
  iface br0 inet dhcp
  bridge_ports eth0
  bridge_fd 9
  bridge_hello 2
  bridge_maxage 12
  bridge_stp off
```
Then use br0 in cockpit or my VMs which will allow the router the give them all local IP addresses via DHCP.

The problem has always been trying to get that IP from the VMs.  As previously stated the ARP table is not a reasonable solution as you have to actually connect somehow to the VM first for the IP to then show up in the table (chicken and egg).

**Comment by zippy2** [comment]
> agent has never worked for me.

Well, maybe that is the area you should focus on then.

> 
> Im not the best at the networking part but for my hypervisor I typically setup a bridge like so:
> apt-get -y install bridge-utils ifupdown
> 
> then in /etc/network/interfaces I do:
> 
> ```
> auto lo
>   iface lo inet loopback
> allow-hotplug eth0
> auto br0
>   iface br0 inet dhcp
>   bridge_ports eth0
>   bridge_fd 9
>   bridge_hello 2
>   bridge_maxage 12
>   bridge_stp off
> ```

Nothing obviously wrong here.

> 
> Then use br0 in cockpit for my VMs which will allow the router the give them all local IP addresses via DHCP.
> 
> The problem has always been trying to get that IP from the VMs. As previously stated the ARP table is not a reasonable solution as you have to actually connect somehow to the VM first for the IP to then show up in the table (chicken and egg).

I think we are clear that ARP is not the best approach (although it's interesting that the host ARP table was not filled in during DHCP). What I don't understand is why isn't the network wide DHCP also doing DNS. I mean, forget virtualization for a moment and imagine you plug a new computer to your LAN (that's effectively what's happening with your bridge anyway). How come 'ping $newhost' doesn't work?

Also, you did not provide any (clever) way to detect IP addresses, so "libcrap" could be extended. Maybe it's not the best idea to call it "crap" if you want help from its developers? Because at this point I've almost lost interest in helping you. So go figure.

**Comment by tgwaste** [comment]
>Also, you did not provide any (clever) way to detect IP addresses, so "libcrap" could be extended. Maybe it's not the best idea to call it "crap" if you want help from its developers? Because at this point I've almost lost interest in helping you. So go figure.

You haven't helped me even in the slightest.  Are you the developer of libvirt?  If you are I certainly should not be required to give you any clever method of obtaining IP addresses.  You should already know how to do that.  As far as a "Fix" I assume the developer of cockpit would need to figure that part out.

If you want cleverness: I suppose you could do a quick ping of all IP addresses on the local nets class C which would probably then make the ones that replied appear in the arp table.

Thats just a theory though.

**Comment by ntruhan** [comment]
> > Also, you did not provide any (clever) way to detect IP addresses, so "libcrap" could be extended. Maybe it's not the best idea to call it "crap" if you want help from its developers? Because at this point I've almost lost interest in helping you. So go figure.
> 
> You haven't helped me even in the slightest. Are you the developer of libvirt? If you are I certainly should not be required to give you any clever method of obtaining IP addresses. You should already know how to do that. As far as a "Fix" I assume the developer of cockpit would need to figure that part out.
> 
> If you want cleverness: I suppose you could do a quick ping of all IP addresses on the local nets class C which would probably then make the ones that replied appear in the arp table.
> 
> Thats just a theory though.

That is the solution I came up with last year and listed in the thread above.  Copied here as well for reference:
#!/bin/bash
network=192.168.2.1/24
if [ "$#" -ne 1 ]; then echo Usage example: $0 aa:bb:cc:dd:ee:ff; exit 2; fi;
nmap -sP -T4 $network >& /dev/null
ip=$(arp -n | grep $1 | awk ' { print $1 }')
ping $ip -n -q -c 2 -i 0.2 -w 1 >& /dev/null
if [ $? -eq 0 ]; then
echo Device is online ($ip)
else
echo Device is offline
exit 1
fi;

I did an NMAP scan over just a standard ping of the subnet since the nmap ping seemed to give me better results and cached the results in the arp table.  Then query the arp table for the mac and get the IP.
Now the last part was just a check to see if it was actually responding or not.

I threw this in a shell script and since I knew the MAC, I just called the script, passed in the MAC and got the IP back.
Now I didn't have the time to pull the project down locally and code it, then got side-tracked, but it could be broken down into a sub-page or something with a button to retrieve IP addresses which would do this scan and spit out the IP addresses that match the MAC addresses in the table.

It does take a couple seconds to run, so not immediate response, but it does provide them, and there may be a more efficient way to code it, I just know it worked for me.

**Comment by tgwaste** [comment]
> It does take a couple seconds to run, so not immediate response, but it does provide them, and there may be a more efficient way to code it, I just know it worked for me.
You could probably pipe all the tries through xargs in a threaded manner to do it all much quicker.

**Comment by KKoukiou** [comment]
I sent a PR to fix this issue.
We were only parsing the IPs with the leases source which indeed will not provide IPs for NICs with bridge source type.
