### ISSUE TITLE
Networking problem

### ISSUE THREAD

**Issue by L25inux** [cockpit-project/cockpit-machines#782]
Hello, I have this issue with networking in Cockpit service - virtual machines. I have installed it on Ubuntu 20.04. 

My goal is have virtual machines managed under cockpit interface. I want every virtual machine to have connected to our internal network but I am not able to configure it via Networking tab. What and how I should configure networking in cockpit, please? I am not able to see network inside virtual machine :( 
Thank you for help :) 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/69634168/181751523-4b2fff4a-674a-4aea-8422-72afb0de4649.png">
<img width="1362" alt="c" src="https://user-images.githubusercontent.com/69634168/181752341-3c4548ad-98b1-4b57-9454-2ba766a78b93.png">

**Comment by skobyda** [comment]
Since you want to attach multiple VMs to basically one bridge, I would recommend trying out NAT virtual network:
![Screenshot from 2022-08-29 12-42-22](https://user-images.githubusercontent.com/42733240/187183803-9f2c4ad1-f4ae-4a2e-84e6-15e2a4298467.png)
 You can configure it to attach to your specific network device
