### ISSUE TITLE
"Virtualization service (libvirt) is not active" after installation

### ISSUE THREAD

**Issue by KrzysztofPlaczek** [cockpit-project/cockpit-machines#832]
I got this message after installation of cockpit-machines. Libvirt local socket and libvirtd.service are both running fine. Is there something i can do to get rid of the message and start using the plugin? 
![image](https://user-images.githubusercontent.com/109726216/196627066-3c8c79cb-3a6d-4dca-b8c4-d6be176b7b17.png)

**Comment by KrzysztofPlaczek** [comment]
Just in case someone stumbles across issue like this. This is the solution that helped for me in case like described above. 
https://github.com/cockpit-project/cockpit/issues/13343#issuecomment-570611574

```# ======
# install cockpit on ubuntu 19.10
sudo apt-get install -y cockpit cockpit-machines libvirt-dbus

# fix for issue 'machines list is empty'
# https://github.com/cockpit-project/cockpit/issues/13343
sudo usermod -a -G libvirt libvirtdbus
sudo usermod -a -G libvirt libvirt-qemu

# must reboot (or restart the affected systemd services) for changes to take effect

**Comment by garrett** [comment]
Ubuntu 19.10 is extremely old at this point and would have a very old version of Cockpit. Any changes we make now won't show up for you (or anyone else) on 19.10.

19.10 actually reached EOL status _over 2 years ago!_ You should've upgraded before mid-July of 2020! Your system is extremely out of date and has a lot of bugs, including severe security issues.

https://itsfoss.com/ubuntu-19-10-end-of-life/

If you don't want to do a major upgrade every year, look into long term support distributions, such as [Ubuntu LTS](https://ubuntu.com/download/server) (Ubuntu Server LTS linked; [Ubuntu LTS desktop](https://ubuntu.com/download/desktop/thank-you?version=22.04.1&architecture=amd64) is also available) which end with .04 instead of .10, such as 22.04, [CentOS Stream 9](https://centos.org/download/), [Alma Linux 9](https://almalinux.org/), [Rocky Linux 9](https://rockylinux.org/download), [openSUSE Leap](https://get.opensuse.org/leap/15.4/), and, of course, [Debian Stable](https://www.debian.org/releases/stable/).

For commercial offerings, there's [Red Hat Enterprise Linux](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux), [SUSE Linux Enterprise Server](https://www.suse.com/products/server/), and [Ubuntu has paid support](https://ubuntu.com/pricing) for their LTS too. But, as your distro choice is wildly out of date and a community version, I assume you'd probably want one of the ones mentioned in the previous paragraph.

With all this said, the smoothest update for you would be to (_back up_ and then) do an in-place upgrade to Ubuntu LTS. [The ItsFoss article linked above](https://itsfoss.com/ubuntu-19-10-end-of-life/) talks about upgrading to 20.04, which is based on 19.10, so it's probably the best path for you for right now. However, if you're doing a fresh re-installation, you'd want to choose the most up to date version of whatever distro (mentioned in the above paragraph) for more current packages (including Cockpit).

I'm not sure if upgrading in-place from 19.10 to 22.04 would work (theoretically, it might), but you could probably go from 19.10 to 20.04 to 22.04 just fine. (Or upgrade to and stay on 20.04 for now.)

Ubuntu's release cycle page @ https://ubuntu.com/about/release-cycle explains their release cycle well and includes this graphic:

![support timeline](https://user-images.githubusercontent.com/10246/196657520-c5de2520-c1ce-4706-aa95-f006f8c4cde6.png)

All the other "long term", "stable", "enterprise" distributions mentioned above have a similar concept for updates and (some level of) support (free and/or paid, depending on which distribution) as well.

**Comment by KrzysztofPlaczek** [comment]
I run ubuntu 22.04. I just pasted the information from the comment that i linked in my previous comment. So the information about the ubuntu 19 is about my machine. The point is that this solution worked now or 2 years ago.

**Comment by garrett** [comment]
With everything said above, if this is still happening in current versions of Cockpit on a currently supported version of Ubuntu, then:

1. Cockpit could make sure `libvirt-dbus` is a dependency (if it isn't already and is needed).
2. The error message is not correct, unless the service is installed and configured properly and is actually not running.
   - In other words: Why is the service not running? We should show the root cause, not a symptom.
   - We wouldn't be able to answer every reason why it isn't running, but we could do a check for the problems mentioned here, including.
3. Cockpit-Machines should _also_ check to make sure the services has the correct groups.

It would be awesome if Cockpit itself could fix the issue, but we should at a minimum explain what the problem is and suggest a solution (even if that needs to be run manually, like "libvirt is not properly configured. Please run `sudo usermod -a -G libvirt libvirtdbus libvirt-qemu` in a terminal as an administrator.).

Re-opening this issue with a request to check if it's still a problem in current versions of Cockpit on supported versions of Ubuntu.

If it's no longer a problem, we can close this again. If it is still a problem, then we should fix it, as outlined above.

**Comment by garrett** [comment]
> I run ubuntu 22.04. I just pasted the information from the comment that i linked in my previous comment. So the information about the ubuntu 19 is about my machine. The point is that this solution worked now or 2 years ago.

Aha! OK. Great! :+1:

I elaborated just in case someone else having the same problem with an older version of Ubuntu might stumble across this too. (I usually try to not cause the xkcd forum problem: https://m.xkcd.com/979/ where someone else might stumble across old information without an update.)

If you're still having the issue in 22.04, then we still need to fix it as I suggest above.

**Comment by garrett** [comment]
Oh, I just noticed in https://github.com/cockpit-project/cockpit/issues/13343#issuecomment-701105435, it says:

> DO NOT add the `libvirt-qemu` user to the libvirt group, or VMs may be able to access the socket, which would open up a security hole.

Your comment above, https://github.com/cockpit-project/cockpit-machines/issues/832#issuecomment-1283582268, mentions adding it. So you might want to remove `libvirt-qemu` from the `libvirt` group on your system... if you followed the quote in your comment verbatim.

**Comment by snuggles4553** [comment]
> It would be awesome if Cockpit itself could fix the issue, but we should at a minimum explain what the problem is and suggest a solution (even if that needs to be run manually, like "libvirt is not properly configured. Please run `sudo usermod -a -G libvirt libvirtdbus` in a terminal as an administrator.).

@garrett Today, I still needed to perform the suggested workaround on a fresh AlmaLinux 10.0 installation.
```
usermod -a -G libvirt libvirtdbus
reboot
```

This fixed the error shown by Cockpit: `Virtualization service (libvirt) is not active`

Although the Cockpit message is inaccurate (`libvirtd.service` was actually running), it seems strange that a default installation of the `libvirt-dbus` package does not add the `libvirtdbus` user to the `libvirt` group. Then again, perhaps it's an intentional design choice, to limit the `libvirtdbus` user's access rights to the minimum needed. Then again, `systemctl cat libvirt-dbus` shows that `libvirt` is defined in the systemd `SupplementaryGroups` directive...

```
$ systemctl cat libvirt-dbus
# /usr/lib/systemd/system/libvirt-dbus.service
[Unit]
Description=Libvirt DBus Service

[Service]
BusName=org.libvirt
DynamicUser=yes
User=libvirtdbus
Group=libvirtdbus
SupplementaryGroups=libvirt
ExecStart=/usr/sbin/libvirt-dbus --system

[Install]
Alias=org.libvirt.service
```
