### ISSUE TITLE
Feature Request: Snapshot and Backup System

### ISSUE THREAD

**Issue by tgwaste** [cockpit-project/cockpit-machines#90]
It would be cool if there was a way to make a snapshot or have automatic backups.

This is how I like to make my backups via CLI if it gives any ideas:

virsh suspend domain
rsync -avP /var/lib/libvirt/images/domain.qcow2 /bak/
virsh resume domain
gzip /bak/domain.qcow2

virsh also has snapshot stuff built in already.

```
# virsh help | grep snapshot-
    snapshot-create                Create a snapshot from XML
    snapshot-create-as             Create a snapshot from a set of args
    snapshot-current               Get or set the current snapshot
    snapshot-delete                Delete a domain snapshot
    snapshot-dumpxml               Dump XML for a domain snapshot
    snapshot-edit                  edit XML for a snapshot
    snapshot-info                  snapshot information
    snapshot-list                  List snapshots for a domain
    snapshot-parent                Get the name of the parent of a snapshot
    snapshot-revert                Revert a domain to a snapshot
```

**Comment by KKoukiou** [comment]
Hi @tgwaste the snapshots commands are available from the cockpit-machines UI since release 225. You can create a snapshots, revert and delete an exiting one. 

See https://cockpit-project.org/blog/cockpit-225.html.

I guess you 're using a version before that. For the snapshots section to show up libvirt-dbus > = v1.4.0 is needed., which indeed does not exist in many distros yet. If this is the issue for you, I suggest installing the package manually.

**Comment by KKoukiou** [comment]
@tgwaste so I will close this issue, since it's already implemented functionality. If you have trouble updating you packages to make this feature appear, let's continue this in the 'Discussions' section.
