### ISSUE TITLE
VNC console is cut off

### ISSUE THREAD

**Issue by cobi-s** [cockpit-project/cockpit-machines#922]
The issue was already brought up in the cockpit issue tracker: https://github.com/cockpit-project/cockpit/issues/8392

Unfortunately, with versions 274 and 281 (haven't tested other versions), the issue is still present for me. I can reproduce the issue when the anaconda installer (Fedora and similar images) pops up. After a successful installation, the resizing of the VNC window works fine though.

The described workaround, resizing the browser window, does not help. Using remote-viewer is also not an option for me.

**Comment by garrett** [comment]
I see this too, in Firefox:

![image](https://user-images.githubusercontent.com/10246/215771539-c4078a79-693f-4f77-a480-db7495eb7725.png)

At least for the time being, for Debian's text based installer, switching to expanded mode helps:

![image](https://user-images.githubusercontent.com/10246/215771657-04c86172-cf95-4dbe-a7d1-99d1a2f1b651.png)

In Fedora Rawhide, it fits, but it's cramped:

![image](https://user-images.githubusercontent.com/10246/215774043-c14825a1-4e91-442d-b1b2-2c04e9eb76ec.png)

Until you proceed, then some parts are cropped off:

![image](https://user-images.githubusercontent.com/10246/215774152-c513ecb6-be83-4256-ba9c-af5de0ca3086.png)

![image](https://user-images.githubusercontent.com/10246/215774347-0b31bcee-7c11-453b-bcdd-a8dbb7226673.png)


But it's fine in expanded mode:
![image](https://user-images.githubusercontent.com/10246/215774209-c97e0636-fb27-4c35-a5cc-ffcabf25978d.png)

![image](https://user-images.githubusercontent.com/10246/215774403-d6213055-d8b5-4652-8950-2529b211199a.png)

I know that the smaller preview in-page used to scale things down, and it seems to in some cases. So I guess we had a regression. (However, in scaled down mode, sometimes it wouldn't scale the mouse movements to match, so the mouse position was in a different area than it should've been. Expanded mode fixed that too, as they matched up. It's due to the component we're using. It probably has changed a bit and caused this regression.)
