### ISSUE TITLE
Drop publish-dist retry loop

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit-machines#93]
I don't like this loop, and I think we should be doing this differently:

 - on pull requests, we should push only a tag, as a commit on top of the most recent commit on the main branch.
 - on merge to main, we then push an update also to the main branch here

random PRs ending up on the main branch seems weird, and is also exactly the source of the potential conflict here.

thoughts?

_Originally posted by @allisonkarlitskaya in https://github.com/cockpit-project/cockpit-machines/pull/84#discussion_r611433209_

**Comment by martinpitt** [comment]
I generally like your idea about pushing to main only for main builds. However, wouldn't we still need the same retry loop? If you land two PRs closely together, one of their publish-dist runs will still lose the race and needs to be retried. It would just be less likely.

**Comment by martinpitt** [comment]
I just found https://github.com/softprops/turnstyle which we may use to serialize parallel publish-dist runs. That's just some kind of "busy retry loop" for some semaphore (not sure how it's actually implemented,  I didn't look yet), but that already looks more elegant than our retry loop. 

Allegedly, [github is looking into fixing this properly](https://github.community/t/prevent-parallel-workflows/16370), too.

**Comment by allisonkarlitskaya** [comment]
There's another potentially thorny issue here: we want to serialize the `publish-dist` on main merges, but not on PRs (since those will generate unique tags and can run concurrently to each other without problem at all).

Unfortunately, in both cases, we trigger the workflow on the completion of `build-dist`.

We need a way to distinguish "build-dist that ran because of a PR proposal" (in which case, no turnstyle and no main update) vs. "build-dist that run because of a main merge" (in which case, serialization and main update).  Deciding to update main or not is probably not too tricky, but conditionalising the turnstyle use might get thorny.

Alternative, of course is to have two separate `build-dist` workflows, but that seems awful.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : That seems fine. In publish-dist we can add a `pr-info.json` file to the artifact, so that publish-dist can do that differentiation. Then the turnstyle step can be conditionalized on whether it's a PR, and so can the `git push HEAD`.

**Comment by martinpitt** [comment]
This hasn't been an issue for a while any more, since we switched to disconnected tags.
